TRUNCATE TABLE Kolcsonzesek;
TRUNCATE TABLE Kolcsonzo;
TRUNCATE TABLE FilmekDVDn;
TRUNCATE TABLE Filmek;
TRUNCATE TABLE Mufajok;
TRUNCATE TABLE DVDk;
TRUNCATE TABLE Kolcsonzesek_archive;
TRUNCATE TABLE Kolcsonzok_archive;